In [4]:
#the normal equation
import numpy as np
np.random.seed(42)
m = 100
X = 2 * np.random.rand(m,1)
y = 4 + 3 * X + np.random.rand(m,1)

In [5]:
from sklearn.preprocessing import add_dummy_feature

X_b = add_dummy_feature(X)
theta_best = np.linalg.inv(X_b.T @ X_b) @ X_b.T @ y
theta_best

array([[4.51359766],
       [2.98323418]])

In [6]:
#LinearRegression class is based on the scipy.linalg.lstsq() function
theta_best_svd, residuals, rank, s = np.linalg.lstsq(X_b, y, rcond = 1e-6)
theta_best_svd

array([[4.51359766],
       [2.98323418]])

In [7]:
#This function computes pseudoinverse of X (specifically, the Moore-Penrose inverse)
np.linalg.pinv(X_b)@y

array([[4.51359766],
       [2.98323418]])

In [ ]:
#When using Gradient Descent, you should ensure that all features have a similar 
#scale (e.g., using Scikit-Learn’s StandardScalerclass), or else it will take much longer to converge